overrides:
  ceph:
    log-whitelist:
    - but it is still running
    - objects unfound and apparently lost
    conf:
      mon:
        mon osd max initial pgs: 1024
tasks:
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgnum_shrink: 1
    chance_pgpnum_fix: 1
